language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required

before_install:
  - if [[ $VCMI_PLATFORM == 'linux' ]]; then . .travis.linux; fi
  - if [[ $VCMI_PLATFORM == 'mac' ]]; then . .travis.osx; fi
  - if [[ $VCMI_PLATFORM == 'mxe' ]]; then . .travis.mxe; fi

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" .. $VCMI_CMAKE_FLAGS

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then cd ..; xcodebuild -project osx/osx-vcmibuilder/vcmibuilder.xcodeproj/ -configuration Release CONFIGURATION_BUILD_DIR=..; cd build; fi
  - make -j2

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=libstdc++-4.8-dev
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.5 REAL_CXX=clang++-3.5 PACKAGE=clang-3.5 SUPPORT=libstdc++-4.8-dev
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.6 REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=libstdc++-4.8-dev
    - os: linux
      compiler: gcc
      env: VCMI_PLATFORM='linux' REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=
    - os: linux
      env: VCMI_PLATFORM='mxe' MXE_TARGET=i686-w64-mingw32.shared VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
      sudo: required
    - os: osx
      env: VCMI_PLATFORM='mac'

notifications:
  email:
    recipients:
      - vcmi.fail@mixaill.tk
      - saven.ivan@gmail.com
    on_success: change
    on_failure: always
